---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The YEP (Yellow Fever Epidemic Prevention) package is designed to aid infectious disease researchers in simulating yellow fever transmission both in regions where it is currently endemic and in regions where it may potentially be introduced in the future due to human movement and climate change. Potential applications include:

-   Projection of yellow fever burden (numbers of cases and deaths, absolute and/or reported) in a region based on epidemiological parameters
-   Estimation of the risk of an outbreak above a certain size (of absolute or reported cases) in a region
-   Simulation of the effect on epidemiological outcomes of planned or hypothetical vaccination campaigns and/or ongoing routine programs
-   Estimation of epidemiological parameters based on available data of particular types (serological survey results and reported case numbers)

[Yellow fever Fact Sheet - World Health Organization](https://www.who.int/news-room/fact-sheets/detail/yellow-fever)

The yellow fever virus is transmitted by multiple mosquito species (from genii including Aedes, Haemagogus and Sabethes) and in addition to humans, affects non-human primates (NHPs) including both Old World and New World monkeys. It originates in Africa but was transmitted to the Americas following European colonization. The existence of a sylvatic reservoir in wild NHPs makes eradicating the virus worldwide effectively impossible. There are no specific treatments for yellow fever; the primary control methods are suppression of mosquito vectors in inhabited areas and a vaccine which has been available since 1938 and remained effective. Further complicating efforts to control yellow fever is the lack of rapid diagnostic tests or systematic testing programs; most yellow fever cases, especially those with no or mild symptoms, go undiagnosed.

An estimated 12% of infections lead to severe symptoms (including jaundice, bleeding and liver failure), with around 40-50% of severe cases leading to death [REF], for an overall infection fatality rate of around 5-6%. This is much higher than many common infectious diseases such as malaria, influenza or measles, resulting in a high death toll as a proportion of the population in large outbreaks such as historical ones in cities such as Manaus (Brazil) and New Orleans (USA) [REF].

The estimated number of yellow fever cases worldwide in 2013 was 84,000-170,000 with 29,000-60,000 deaths [REF].

References: \*
