---
title: "Worked Example 1 - Single Model Run"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Worked Example 2 - Running Model For Multiple Parameter Sets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This worked example demonstrates how to [TBA]

```{r,eval=FALSE}
library(YEP)
input_data <- readRDS(file = paste(path.package("YEP"), 
                                   "/exdata/input_data_example.Rds", sep = ""))
n_regions <- length(input_data$region_labels)
```

[TBA]

```{r,eval=FALSE}
# Force of infection due to spillover from sylvatic reservoir
FOI_spillover <- rep(1.0e-8,n_regions)
# Basic reproduction number for urban spread of infection
R0 <- rep(1.5,n_regions)
# TBA
vacc_data <- input_data$vacc_data
# TBA
pop_data <- input_data$pop_data 
# Year(s) for which data is to be output
years_data <- c(2000)
# SEIRV data from end of a previous run to use as input (if mode_start = 2; not 
# used here and hence set to NULL)
start_SEIRV <- NULL    
# TBA
output_type <- "full"             
# First year in population/vaccination data (here taken from the input data set; 
# if the population and vaccination data is set manually, this similarly needs 
# to be set manually)
year0 <- input_data$years_labels[1]
# Flag indicating how to set initial population immunity level in addition to
# vaccination
# If mode_start = 0, only vaccinated individuals are immune (R = 0)
# If mode_start = 1, shift some non-vaccinated individuals into recovered to 
# give herd immunity (R = 1 - 1/R0)
# If mode_start = 2, use SEIRV input in list from previous run(s), set using
# start_SEIRV variable
mode_start <- 1  
# Proportional vaccine efficacy (from 0 to 1); probability of vaccination 
# successfully providing immunity (i.e. moving vaccinated individual to group V)
vaccine_efficacy <- 1.0       
# Time increment in days to use in model (should be 1.0, 2.5 or 5.0 days)
dt <- 1.0            
# Number of particles to run
n_particles <- 10     
# Number of threads to run
n_threads <- 1   
# TBA
deterministic <- FALSE
```

We use the Model_Run_Multi() function to run the model for the inputs above:

```{r,eval=FALSE}
test1 <- Model_Run_Multi(FOI_spillover, R0, vacc_data, pop_data, years_data,
                         start_SEIRV, output_type, year0, mode_start, vaccine_efficacy, 
                         dt, n_particles, n_threads, deterministic)
```
