// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_time(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// SEIRV_Model.cpp
SEXP dust2_system_SEIRV_Model_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_time(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// SEIRV_Model_mr01_basic.cpp
SEXP dust2_system_SEIRV_Model_mr01_basic_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr01_basic_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr01_basic_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_time(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// SEIRV_Model_mr02_sero.cpp
SEXP dust2_system_SEIRV_Model_mr02_sero_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr02_sero_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr02_sero_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_time(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// SEIRV_Model_mr03_infs.cpp
SEXP dust2_system_SEIRV_Model_mr03_infs_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr03_infs_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr03_infs_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_time(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_system_SEIRV_Model_mr04_fit_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_system_SEIRV_Model_mr04_fit_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_SEIRV_Model_mr04_fit_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_unfilter_SEIRV_Model_mr04_fit_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_SEIRV_Model_mr04_fit_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_rng_state(cpp11::sexp ptr);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// SEIRV_Model_mr04_fit.cpp
SEXP dust2_filter_SEIRV_Model_mr04_fit_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _YEP_dust2_filter_SEIRV_Model_mr04_fit_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_SEIRV_Model_mr04_fit_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_alloc",               (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_alloc,               9},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_snapshots",      (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_snapshots,      4},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_state",          (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_state,          4},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_trajectories",   (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_trajectories,   4},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_rng_state",           (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_rng_state,           1},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_run",                 (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_run,                 9},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_set_rng_state",       (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_set_rng_state,       2},
    {"_YEP_dust2_filter_SEIRV_Model_mr04_fit_update_pars",         (DL_FUNC) &_YEP_dust2_filter_SEIRV_Model_mr04_fit_update_pars,         3},
    {"_YEP_dust2_system_SEIRV_Model_alloc",                        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_alloc,                        8},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_alloc",             (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_alloc,             8},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_reorder",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_reorder,           2},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_rng_state",         (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_rng_state,         1},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_run_to_time",       (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_run_to_time,       2},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_set_rng_state",     (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_set_rng_state,     2},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state",         (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state,         2},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state_initial", (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state_initial, 1},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_set_time",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_set_time,          2},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_simulate",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_simulate,          5},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_state",             (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_state,             6},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_time",              (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_time,              1},
    {"_YEP_dust2_system_SEIRV_Model_mr01_basic_update_pars",       (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr01_basic_update_pars,       2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_alloc",              (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_alloc,              8},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_reorder",            (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_reorder,            2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_rng_state",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_rng_state,          1},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_run_to_time",        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_run_to_time,        2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_set_rng_state",      (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_set_rng_state,      2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state,          2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state_initial",  (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state_initial,  1},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_set_time",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_set_time,           2},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_simulate",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_simulate,           5},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_state",              (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_state,              6},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_time",               (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_time,               1},
    {"_YEP_dust2_system_SEIRV_Model_mr02_sero_update_pars",        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr02_sero_update_pars,        2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_alloc",              (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_alloc,              8},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_reorder",            (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_reorder,            2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_rng_state",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_rng_state,          1},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_run_to_time",        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_run_to_time,        2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_set_rng_state",      (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_set_rng_state,      2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state",          (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state,          2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state_initial",  (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state_initial,  1},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_set_time",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_set_time,           2},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_simulate",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_simulate,           5},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_state",              (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_state,              6},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_time",               (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_time,               1},
    {"_YEP_dust2_system_SEIRV_Model_mr03_infs_update_pars",        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr03_infs_update_pars,        2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_alloc",               (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_alloc,               8},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_compare_data",        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_compare_data,        4},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_reorder",             (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_reorder,             2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_rng_state",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_rng_state,           1},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_run_to_time",         (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_run_to_time,         2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_set_rng_state",       (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_set_rng_state,       2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state",           (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state,           2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state_initial",   (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state_initial,   1},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_set_time",            (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_set_time,            2},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_simulate",            (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_simulate,            5},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_state",               (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_state,               6},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_time",                (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_time,                1},
    {"_YEP_dust2_system_SEIRV_Model_mr04_fit_update_pars",         (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_mr04_fit_update_pars,         2},
    {"_YEP_dust2_system_SEIRV_Model_reorder",                      (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_reorder,                      2},
    {"_YEP_dust2_system_SEIRV_Model_rng_state",                    (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_rng_state,                    1},
    {"_YEP_dust2_system_SEIRV_Model_run_to_time",                  (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_run_to_time,                  2},
    {"_YEP_dust2_system_SEIRV_Model_set_rng_state",                (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_set_rng_state,                2},
    {"_YEP_dust2_system_SEIRV_Model_set_state",                    (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_set_state,                    2},
    {"_YEP_dust2_system_SEIRV_Model_set_state_initial",            (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_set_state_initial,            1},
    {"_YEP_dust2_system_SEIRV_Model_set_time",                     (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_set_time,                     2},
    {"_YEP_dust2_system_SEIRV_Model_simulate",                     (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_simulate,                     5},
    {"_YEP_dust2_system_SEIRV_Model_state",                        (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_state,                        6},
    {"_YEP_dust2_system_SEIRV_Model_time",                         (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_time,                         1},
    {"_YEP_dust2_system_SEIRV_Model_update_pars",                  (DL_FUNC) &_YEP_dust2_system_SEIRV_Model_update_pars,                  2},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_alloc",             (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_alloc,             8},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots",    (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots,    4},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_state",        (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_state,        4},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories", (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories, 4},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_run",               (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_run,               9},
    {"_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_update_pars",       (DL_FUNC) &_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_update_pars,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_YEP(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
