# Generated by cpp11: do not edit by hand

dust_SEIRV_Model_gpu_info <- function() {
  .Call(`_YEP_dust_SEIRV_Model_gpu_info`)
}

dust_cpu_SEIRV_Model_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_SEIRV_Model_capabilities <- function() {
  .Call(`_YEP_dust_cpu_SEIRV_Model_capabilities`)
}

dust_cpu_SEIRV_Model_run <- function(ptr, r_time_end) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_run`, ptr, r_time_end)
}

dust_cpu_SEIRV_Model_simulate <- function(ptr, time_end) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_simulate`, ptr, time_end)
}

dust_cpu_SEIRV_Model_set_index <- function(ptr, r_index) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_set_index`, ptr, r_index)
}

dust_cpu_SEIRV_Model_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_SEIRV_Model_state <- function(ptr, r_index) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_state`, ptr, r_index)
}

dust_cpu_SEIRV_Model_time <- function(ptr) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_time`, ptr)
}

dust_cpu_SEIRV_Model_reorder <- function(ptr, r_index) {
  invisible(.Call(`_YEP_dust_cpu_SEIRV_Model_reorder`, ptr, r_index))
}

dust_cpu_SEIRV_Model_resample <- function(ptr, r_weights) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_resample`, ptr, r_weights)
}

dust_cpu_SEIRV_Model_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_rng_state`, ptr, first_only, last_only)
}

dust_cpu_SEIRV_Model_set_rng_state <- function(ptr, rng_state) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_set_rng_state`, ptr, rng_state)
}

dust_cpu_SEIRV_Model_set_data <- function(ptr, data, shared) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_set_data`, ptr, data, shared)
}

dust_cpu_SEIRV_Model_compare_data <- function(ptr) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_compare_data`, ptr)
}

dust_cpu_SEIRV_Model_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_SEIRV_Model_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_YEP_dust_cpu_SEIRV_Model_set_n_threads`, ptr, n_threads))
}

dust_cpu_SEIRV_Model_n_state <- function(ptr) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_n_state`, ptr)
}

dust_cpu_SEIRV_Model_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_YEP_dust_cpu_SEIRV_Model_set_stochastic_schedule`, ptr, time))
}

dust_cpu_SEIRV_Model_ode_statistics <- function(ptr) {
  .Call(`_YEP_dust_cpu_SEIRV_Model_ode_statistics`, ptr)
}
