# Generated by cpp11: do not edit by hand

dust2_system_SEIRV_Model_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_time`, ptr)
}

dust2_system_SEIRV_Model_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_rng_state`, ptr)
}

dust2_system_SEIRV_Model_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model2_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model2_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model2_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model2_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_time`, ptr)
}

dust2_system_SEIRV_Model2_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model2_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model2_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model2_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_rng_state`, ptr)
}

dust2_system_SEIRV_Model2_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model2_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model2_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model2_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model2_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}
