# Generated by cpp11: do not edit by hand

dust2_system_SEIRV_Model_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_time`, ptr)
}

dust2_system_SEIRV_Model_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_rng_state`, ptr)
}

dust2_system_SEIRV_Model_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr01_basic_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_mr01_basic_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr01_basic_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr01_basic_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_time`, ptr)
}

dust2_system_SEIRV_Model_mr01_basic_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_mr01_basic_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_mr01_basic_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_mr01_basic_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_rng_state`, ptr)
}

dust2_system_SEIRV_Model_mr01_basic_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_mr01_basic_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr01_basic_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_mr01_basic_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr01_basic_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr02_sero_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_mr02_sero_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr02_sero_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr02_sero_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_time`, ptr)
}

dust2_system_SEIRV_Model_mr02_sero_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_mr02_sero_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_mr02_sero_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_mr02_sero_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_rng_state`, ptr)
}

dust2_system_SEIRV_Model_mr02_sero_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_mr02_sero_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr02_sero_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_mr02_sero_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr02_sero_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr03_infs_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_mr03_infs_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr03_infs_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr03_infs_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_time`, ptr)
}

dust2_system_SEIRV_Model_mr03_infs_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_mr03_infs_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_mr03_infs_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_mr03_infs_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_rng_state`, ptr)
}

dust2_system_SEIRV_Model_mr03_infs_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_mr03_infs_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr03_infs_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_mr03_infs_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr03_infs_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr04_fit_alloc <- function(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_alloc`, r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads)
}

dust2_system_SEIRV_Model_mr04_fit_run_to_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_run_to_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr04_fit_state <- function(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_state`, ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_system_SEIRV_Model_mr04_fit_time <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_time`, ptr)
}

dust2_system_SEIRV_Model_mr04_fit_set_state_initial <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state_initial`, ptr)
}

dust2_system_SEIRV_Model_mr04_fit_set_state <- function(ptr, r_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_set_state`, ptr, r_state)
}

dust2_system_SEIRV_Model_mr04_fit_reorder <- function(ptr, r_index) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_reorder`, ptr, r_index)
}

dust2_system_SEIRV_Model_mr04_fit_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_rng_state`, ptr)
}

dust2_system_SEIRV_Model_mr04_fit_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_set_rng_state`, ptr, r_rng_state)
}

dust2_system_SEIRV_Model_mr04_fit_set_time <- function(ptr, r_time) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_set_time`, ptr, r_time)
}

dust2_system_SEIRV_Model_mr04_fit_update_pars <- function(ptr, pars) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_update_pars`, ptr, pars)
}

dust2_system_SEIRV_Model_mr04_fit_simulate <- function(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_simulate`, ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_SEIRV_Model_mr04_fit_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads)
}

dust2_filter_SEIRV_Model_mr04_fit_alloc <- function(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_alloc`, r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed)
}

dust2_system_SEIRV_Model_mr04_fit_compare_data <- function(ptr, r_data, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_system_SEIRV_Model_mr04_fit_compare_data`, ptr, r_data, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_SEIRV_Model_mr04_fit_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_update_pars`, ptr, r_pars, r_index_group)
}

dust2_unfilter_SEIRV_Model_mr04_fit_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_unfilter_SEIRV_Model_mr04_fit_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_unfilter_SEIRV_Model_mr04_fit_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_SEIRV_Model_mr04_fit_update_pars <- function(ptr, r_pars, r_index_group) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_update_pars`, ptr, r_pars, r_index_group)
}

dust2_filter_SEIRV_Model_mr04_fit_run <- function(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_run`, ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_SEIRV_Model_mr04_fit_last_trajectories <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_trajectories`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_SEIRV_Model_mr04_fit_last_snapshots <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_snapshots`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_SEIRV_Model_mr04_fit_last_state <- function(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_last_state`, ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension)
}

dust2_filter_SEIRV_Model_mr04_fit_rng_state <- function(ptr) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_rng_state`, ptr)
}

dust2_filter_SEIRV_Model_mr04_fit_set_rng_state <- function(ptr, r_rng_state) {
  .Call(`_YEP_dust2_filter_SEIRV_Model_mr04_fit_set_rng_state`, ptr, r_rng_state)
}
