## Automatically generated by odin 1.4.6 - do not edit
SEIRV_Model_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "SEIRV_Model_rhs_dde"),
    dll = "YEP",
    user = c("Cas0", "dP1_all", "dP2_all", "dt", "Exp0", "FOI_spillover",
             "Inf0", "N_age", "n_years", "R0", "Rec0", "steps_inc",
             "steps_inf", "steps_lat", "Sus0", "Vac0", "vacc_rate_annual",
             "vaccine_efficacy", "year0"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("SEIRV_Model_rhs_dde", package = "YEP")
      }
    },

    ## This only does something in delay models
    set_initial = function(step, y, use_dde) {
      .Call("SEIRV_Model_set_initial", private$ptr, step, y, use_dde,
            PACKAGE= "YEP")
    },

    update_metadata = function() {
      meta <- .Call("SEIRV_Model_metadata", private$ptr,
                    PACKAGE = "YEP")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, TRUE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("SEIRV_Model_create", user, PACKAGE = "YEP")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/SEIRV_Model.json", mustWork = TRUE,
                             package = "YEP")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("SEIRV_Model_set_user", private$ptr, user, PACKAGE = "YEP")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(step) {
      .Call("SEIRV_Model_initial_conditions", private$ptr, step, PACKAGE = "YEP")
    },

    rhs = function(step, y) {
      .Call("SEIRV_Model_rhs_r", private$ptr, step, y, PACKAGE = "YEP")
    },

    update = function(step, y) {
      self$rhs(step, y)
    },

    contents = function() {
      .Call("SEIRV_Model_contents", private$ptr, PACKAGE = "YEP")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(step, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_discrete(
        self, private, step, y, ..., use_names = use_names)
    }
  ))


SEIRV_Model <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("SEIRV_Model")
  SEIRV_Model_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(SEIRV_Model) <- "odin_generator"
attr(SEIRV_Model, "generator") <- SEIRV_Model_
